### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ghost** [DrNseven/D3D11-Wallhack#14]
Injecting this into a process overtime takes up all of my ram very quickly.

**Comment by cxmplex** [comment]
Add this to the bottom of your DrawIndexed:

```
		SAFE_RELEASE(rDEPTHBIASState);
		SAFE_RELEASE(rNORMALState);
```

That fixes it for me.

**Comment by cxmplex** [comment]
Nevermind, this simply slows it. I'll do some more digging.
