### ISSUE TITLE
RainbowSix Siege

### ISSUE THREAD

**Issue by DAMNCHEATS** [DrNseven/D3D11-Wallhack#4]
Hi. Thanks for ur WallHack.
Sorry for my bad english.

but for RainbowSix Siege i dont have all stride.

only it:
Stride == 0 && IndexCount == 960 && indesc.ByteWidth == 52428800 && vedesc.ByteWidth == 96
Stride == 24 && IndexCount == 6 && indesc.ByteWidth == 12 && vedesc.ByteWidth == 96

One DirectX 9 logger used it:
pDev->GetTexture(0, &BTEX);
			Found = false;
			for (UINT i = 0; i < BASETEX.size(); i++)
				if (BASETEX[i] == (DWORD)BTEX)
					Found = true;
			if (Found == false)
				BASETEX.push_back
				((DWORD)BTEX);
			if (BASETEX[iBaseTex] == (DWORD)BTEX && Green)

if (GetAsyncKeyState(VK_NUMPAD5) & GetAsyncKeyState(VK_ADD))
			if (iBaseTex < BASETEX.size() - 1)iBaseTex++;

It looks for a lot of different textures. You can add for ur DX11 WallHack maybe its help in the search for textures.

**Comment by DrNseven** [comment]
Rainbox Six Siege does not use DrawIndexed, this should help with model recognition: https://www.unknowncheats.me/forum/1677961-post21.html
