### ISSUE TITLE
It's not working for minimap

### ISSUE THREAD

**Issue by darpangs** [DrNseven/D3D11-Wallhack#8]
This works greatly for 3d graphics. 
But it seems that games does not use those "DrawIndexed" , "Draw"  APIs for drawing HUD such as Minimap.
I've tried to making minimap hack with your this codes, but it works for just 3d characters only. 

Have you ever tried to handle Minimap before? 
Do you think this code should work on Minimap too? ( I may did some mistake on using your codes )

**Comment by hasanalizxc** [comment]
> This works greatly for 3d graphics.
> But it seems that games does not use those "DrawIndexed" , "Draw" APIs for drawing HUD such as Minimap.
> I've tried to making minimap hack with your this codes, but it works for just 3d characters only.
> 
> Have you ever tried to handle Minimap before?
> Do you think this code should work on Minimap too? ( I may did some mistake on using your codes )

Dear darpangs,

Hope you are fine. I read the readme.rd but i didn't understand.

edit universal.cpp -> How will i edit this file? I mean how can i modify or what will i add/remove?

Thanks.

**Comment by darpangs** [comment]
Hi hasanalizxc, 
Unfortunately, I'm not the author of this project. 
I believe DrNSeven is in charge of this space. 
I hope he may reply to your question.
